services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"  # Spring Boot default port exposed in Dockerfile
    # env_file: ./.env  # Uncomment if .env file exists
    # If your app requires a database or other external services, add them below and configure depends_on
    # depends_on:
    #   - postgres
    networks:
      - appnet

# Example external service configuration (uncomment and configure if needed)
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: foodies
#      POSTGRES_PASSWORD: foodiespass
#      POSTGRES_DB: foodiesdb
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U foodies"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - appnet

networks:
  appnet:
    driver: bridge

# Uncomment if you add a database service above
#volumes:
#  pgdata:
#    driver: local
